#!/usr/bin/env python3

from time import localtime, mktime, strftime

start_time = localtime()
print(f"Time started at {strftime('%X', start_time)}")

# Wait for user to stop timer
input("Press 'Enter' to stop the timer ")

stop_time = localtime()
difference = mktime(stop_time) - mktime(start_time)

print(f"Stopped at {strftime('%X', stop_time)}")
print(f"Total time: {int(difference)} seconds.")